import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../public/tailwind.css";
import { AppHeader, AppFooter, MobileMenu } from "./components";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" className="dark text-foreground bg-background">
        <body className={inter.className}>
          <NextUIProvider id="__next">
            <MobileMenu />
            <AppHeader />
            {children}
            <AppFooter />
          </NextUIProvider>
        </body>
      </html>
    </>
  );
}
